# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: charla-monadas
version: '0.0.0'
github: "githubuser/charla-monadas"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: charla-monadas is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - aeson
  - megaparsec
  - text
  source-dirs: library

executables:
  charla-monadas:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - aeson
    - megaparsec
    - base
    - charla-monadas
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  charla-monadas-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - charla-monadas
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  charla-monadas-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - charla-monadas
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
